### ISSUE TITLE
[BUG] [EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by ghostt187** [KitsuneLab-Development/K4-System-MMRanks#3]
15:00:32 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'K4SharedApi.IPlayerAPI' from assembly 'K4-SharedApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at K4SystemMMRanks.PluginK4SystemMMRanks.<Load>b__14_2(CCSPlayerController p)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at K4SystemMMRanks.PluginK4SystemMMRanks.<Load>b__14_0(DynamicHook _)
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by K4ryuu** [comment]
Update your MMranks and K4-System to latest versions both. Also update the shared api.
